
POST http://192.168.0.10:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "Elijah Lee",
    "lat": -33.9049838,
    "lon": 150.9357761
}

###

POST http://192.168.0.10:3000/routes/display HTTP/1.1
Content-Type: application/json

{
    "u_id": 0
}

###

GET http://192.168.0.10:3000/reset HTTP/1.1